name: Deploy to LeanCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 确保使用 Node.js 18

      - name: Install Dependencies and CLI
        working-directory: ./cloud
        run: |
          npm install
          npm install -g lean-cli

      - name: Add npm global bin to PATH
        run: |
          # 获取 npm 全局 bin 路径
          GLOBAL_NPM_BIN=$(npm bin -g)
          echo "Detected npm global bin path: $GLOBAL_NPM_BIN"
          # 将该路径添加到 GitHub Actions 的 PATH
          echo "$GLOBAL_NPM_BIN" >> $GITHUB_PATH
          echo "Current PATH after modification: $PATH" # 打印 PATH 再次确认

      - name: Verify lean-cli is found
        run: |
          # 检查 'lean' 命令是否在 PATH 中
          if command -v lean &> /dev/null
          then
              echo "'lean' command found. Proceeding with deployment."
              lean --version # 确认版本
          else
              echo "Error: 'lean' command not found in PATH."
              exit 127 # 如果找不到，明确报错
          fi

      - name: Deploy to LeanCloud
        run: lean deploy
        env:
          LEANCLOUD_APP_ID: 'jrJXnuJG3a5nR1dilUv27qLp-gzGzoHsz'
          LEANCLOUD_DEPLOY_TOKEN: ${{ secrets.LEAN_DEPLOY_TOKEN }}
