name: Deploy to LeanCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies and CLI
        working-directory: ./cloud
        run: |
          npm install
          npm install -g lean-cli

      - name: Add npm global bin to PATH and Verify
        run: |
          # Get npm global bin path
          GLOBAL_NPM_BIN=$(npm bin -g)
          echo "Detected npm global bin path: $GLOBAL_NPM_BIN"

          # Check if path is empty, if so, exit with error
          if [ -z "$GLOBAL_NPM_BIN" ]; then
            echo "Error: npm global bin path could not be determined. Exiting."
            exit 1
          fi

          # Add the path to GitHub Actions' PATH
          echo "$GLOBAL_NPM_BIN" >> $GITHUB_PATH
          echo "Updated PATH after adding npm bin: $PATH"

          # Verify if 'lean' command is available
          echo "Attempting to find 'lean' command..."
          if command -v lean &> /dev/null
          then
              echo "'lean' command found at: $(which lean)"
              lean --version
          else
              echo "Error: 'lean' command not found in PATH after all attempts."
              exit 127
          fi

      - name: Deploy to LeanCloud
        run: lean deploy
        env:
          LEANCLOUD_APP_ID: 'jrJXnuJG3a5nR1dilUv27qLp-gzGzoHsz'
          LEANCLOUD_DEPLOY_TOKEN: ${{ secrets.LEAN_DEPLOY_TOKEN }}
